# Generated by Django 3.0 on 2021-09-06 10:51

import autoslug.fields
import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(default=2021, max_length=4, unique=True)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='EventDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='event_name')),
                ('year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='event_app.Year')),
            ],
            options={
                'ordering': ('-id',),
                'unique_together': {('year', 'event_name')},
            },
        ),
        migrations.CreateModel(
            name='Attendant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Phone number should be in the format: 08105506606', regex='^[0]\\d{10}$')])),
                ('visitor', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('department', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('eventdetail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendants', to='event_app.EventDetail')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
