# Generated by Django 3.2 on 2021-09-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0002_auto_20210906_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendant',
            name='sex',
            field=models.CharField(blank=True, choices=[('B', 'Brother'), ('S', 'Sister')], max_length=10, null=True),
        ),
    ]
