# Generated by Django 3.2 on 2021-09-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0003_attendant_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendant',
            name='sex',
            field=models.CharField(blank=True, choices=[('brother', 'Brother'), ('sister', 'Sister')], max_length=10, null=True),
        ),
    ]
