# Generated by Django 3.2 on 2021-09-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0004_alter_attendant_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendant',
            name='day',
            field=models.CharField(choices=[('day 1', 'Day 1'), ('day 2', 'Day 2'), ('day 3', 'Day 3'), ('day 4', 'Day 4'), ('day 5', 'Day 5'), ('day 6', 'Day 6'), ('day 7', 'Day 7')], default='day 1', max_length=5),
        ),
        migrations.AlterField(
            model_name='attendant',
            name='level',
            field=models.CharField(choices=[('100', '100'), ('200', '200'), ('300', '300'), ('400', '400'), ('500', '500'), ('600', '600'), ('graduate', 'Graduate')], default='100', max_length=10),
        ),
        migrations.AlterField(
            model_name='attendant',
            name='sex',
            field=models.CharField(blank=True, choices=[('brother', 'Brother'), ('sister', 'Sister')], default='brother', max_length=10, null=True),
        ),
    ]
