# Generated by Django 3.2 on 2021-09-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0005_auto_20210908_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendant',
            name='day',
            field=models.CharField(choices=[('1', 'Day 1'), ('2', 'Day 2'), ('3', 'Day 3'), ('4', 'Day 4'), ('5', 'Day 5'), ('6', 'Day 6'), ('7', 'Day 7')], default='day 1', max_length=5),
        ),
        migrations.AlterField(
            model_name='attendant',
            name='department',
            field=models.CharField(choices=[('Accounting Technology', 'Accounting Technology'), ('Agricultural Economics', 'Agricultural Economics'), ('Agricultural Economics and Extension', 'Agricultural Economics and Extension'), ('Agricultural Engineering', 'Agricultural Engineering'), ('Agricultural Extension and Rural Development', 'Agricultural Extension and Rural Development'), ('Agriculture', 'Agriculture'), ('Anatomy', 'Anatomy'), ('Animal Nutrition and Biotechnology', 'Animal Nutrition and Biotechnology'), ('Animal Production and Health', 'Animal Production and Health'), ('Architecture', 'Architecture'), ('Biochemistry', 'Biochemistry'), ('Chemical Engineering', 'Chemical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Computer Engineering', 'Computer Engineering'), ('Computer Science', 'Computer Science'), ('Crop And Environmental Protection', 'Crop And Environmental Protection'), ('Crop Production And Soil Science', 'Crop Production And Soil Science'), ('Earth Science', 'Earth Science'), ('Economics', 'Economics'), ('Electrical / Electronic Engineering', 'Electrical / Electronic Engineering'), ('Fine / Applied Art', 'Fine / Applied Art'), ('Food Science and Engineering', 'Food Science and Engineering'), ('Information Systems', 'Information Systems'), ('Marketing', 'Marketing'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Medical Biochemistry', 'Medical Biochemistry'), ('Medical Laboratory Technology / Science', 'Medical Laboratory Technology / Science'), ('Medicine and Surgery', 'Medicine and Surgery'), ('Nursing / Nursing Science', 'Nursing / Nursing Science'), ('Nutrition and Dietetics', 'Nutrition and Dietetics'), ('Physics', 'Physics'), ('Physiology', 'Physiology'), ('Pure / Applied Biology', 'Pure / Applied Biology'), ('Pure / Applied Chemistry', 'Pure / Applied Chemistry'), ('Pure / Applied Mathematics', 'Pure / Applied Mathematics'), ('Pure and Industrial Chemistry', 'Pure and Industrial Chemistry'), ('Science Laboratory Technology', 'Science Laboratory Technology'), ('Transport Management Technology', 'Transport Management Technology'), ('Urban and Regional Planning', 'Urban and Regional Planning'), ('Fine and Applied Arts', 'Fine and Applied Arts'), ('Cyber Security', 'Cyber Security')], default='Accounting Technology', max_length=200),
        ),
    ]
