# Generated by Django 3.2 on 2022-11-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0010_alter_attendant_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendant',
            name='matric_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
