# Generated by Django 3.2 on 2022-11-12 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0011_attendant_matric'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendant',
            name='matric',
        ),
        migrations.AddField(
            model_name='eventdetail',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
