# Generated by Django 3.2 on 2022-11-12 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0011_attendant_matric_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendant',
            name='matric_no',
        ),
    ]
