# Generated by Django 3.2 on 2022-11-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0012_auto_20221112_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetail',
            name='slug',
            field=models.SlugField(),
        ),
    ]
