# Generated by Django 3.2 on 2022-11-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0012_remove_attendant_matric_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendant',
            name='matric',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
