# Generated by Django 3.2 on 2022-11-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0013_alter_eventdetail_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetail',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
